### ISSUE TITLE
List of ToDos on the Site

### ISSUE THREAD

**Issue by olamiko** [superibk/FoundationSM#1]
Hi, Can you create a list of next steps to be done on the site as issues so we can know which task to work on and also tick them off?

**Comment by superibk** [comment]
@olamiko  sure, I can do that, we have some already existing requirements and some suggested features. so will do those ones we intend before now

**Comment by olamiko** [comment]
@superibk Awesome, once you list them I can work on some of them too

**Comment by tosincoker26** [comment]
Great Idea bro

**Comment by olamiko** [comment]
@superibk, are there no available issues to be worked on?

**Comment by tosincoker26** [comment]
There sure are a great number of issues left unattended, we were having the
problem of people been unfamiliar with the technology before now hence the
purpose of the work camp. But now a Twillo box has been created to itemize
those necessary changes and some roles assigned.
I will add you and chat you up to discuss the areas of your expertise.

On 27 Dec 2017 17:59, "Omolola Olamide" <notifications@github.com> wrote:

@superibk <https://github.com/superibk>, are there no available issues to
be worked on?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/superibk/FoundationSM/issues/1#issuecomment-354142919>,
or mute the thread

**Comment by olamiko** [comment]
Ok, I have a bit of previous experience using Django, that was why I asked for issues I could start with previously. But i guess your idea is good also
